#!/bin/sh

APP=chromium

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
if test -f ./appimagetool; then
	echo " appimagetool already exists" 1> /dev/null
else
	echo " Downloading appimagetool..."
	wget -q "$(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | sed 's/"/ /g; s/ /\n/g' | grep -o 'https.*continuous.*tool.*86_64.*mage$')" -O appimagetool
fi
if test -f ./pkg2appimage; then
	echo " pkg2appimage already exists" 1> /dev/null
else
	echo " Downloading pkg2appimage..."
	wget -q https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
fi
chmod a+x ./appimagetool ./pkg2appimage
rm -f ./recipe.yml

DEBRELEASE="oldstable"

# CREATING THE APPIMAGE'S RECIPE...
echo "app: chromium
binpatch: true

ingredients:
  dist: $DEBRELEASE
  package: chromium
  sources:
    - deb http://ftp.debian.org/debian/ $DEBRELEASE main contrib non-free
    - deb http://security.debian.org/$DEBRELEASE-security/ $DEBRELEASE-security main contrib non-free
    - deb http://ftp.debian.org/debian/ $DEBRELEASE-updates main contrib non-free
  packages:
    - chromium" >> recipe.yml

mkdir -p ./$APP/$APP.AppDir
cd ./$APP

# ...DOWNLOAD THE DEB PACKAGES...
# Choose a source manually

_chromium_from_debian() {
	wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/$(curl -Ls https://packages.debian.org/$DEBRELEASE/amd64/chromium/download | grep Download | head -1 | grep -o -P '(?<=Selection -- ).*(?=</title)')
	wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/$(curl -Ls https://packages.debian.org/$DEBRELEASE/amd64/chromium-common/download | grep Download | head -1 | grep -o -P '(?<=Selection -- ).*(?=</title)')
	wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/$(curl -Ls https://packages.debian.org/$DEBRELEASE/amd64/chromium-driver/download | grep Download | head -1 | grep -o -P '(?<=Selection -- ).*(?=</title)')
	wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/$(curl -Ls https://packages.debian.org/$DEBRELEASE/all/chromium-l10n/download | grep Download | head -1 | grep -o -P '(?<=Selection -- ).*(?=</title)')
	wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/$(curl -Ls https://packages.debian.org/$DEBRELEASE/amd64/chromium-sandbox/download | grep Download | head -1 | grep -o -P '(?<=Selection -- ).*(?=</title)')
}

if ! test -f ./chromium_*.deb; then
	_chromium_from_debian
fi
VERSION=$(ls . | sort | grep -o -P '(?<=chromium_).*(?=_amd64)' | head -1)

# ...BUILD THE APPIMAGE...
cd ..
./pkg2appimage ./recipe.yml

# ...REPLACING THE EXISTING APPRUN WITH A CUSTOM ONE...
rm -R -f ./$APP/$APP.AppDir/AppRun
cat >> ./$APP/$APP.AppDir/AppRun << 'EOF'
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${PATH}"
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${HERE}"/usr/lib/python*/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/:"${HERE}"/usr/lib/python*/
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
exec ${HERE}/usr/lib/chromium/chromium "$@"
EOF
chmod a+x ./$APP/$APP.AppDir/AppRun

# ...EXPORT THE APPDIR TO AN APPIMAGE!
ARCH=x86_64 VERSION=$(./appimagetool -v | grep -o '[[:digit:]]*') ./appimagetool -s ./$APP/$APP.AppDir
cd ..
mv ./tmp/*.AppImage ./Chromium_Web_Browser-$VERSION-x86_64.AppImage
